/* eslint-disable */
/**
 * Generated API types for Convex
 *
 * This file is auto-generated by running `npx convex dev`
 * For now, this is a manually created stub until Convex is properly configured.
 */

import { AnyDataModel } from "convex/server";
import type * as personas from "../personas";
import type * as experiments from "../experiments";
import type * as users from "../users";
import type * as responses from "../responses";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: {
  personas: {
    listByUser: typeof personas.listByUser;
    get: typeof personas.get;
    create: typeof personas.create;
    update: typeof personas.update;
    remove: typeof personas.remove;
  };
  experiments: typeof experiments;
  users: typeof users;
  responses: typeof responses;
};

export declare const api: typeof fullApi;
