/* eslint-disable */
/**
 * Generated API stub for Convex
 *
 * This file is auto-generated by running `npx convex dev`
 * For now, this is a manually created stub until Convex is properly configured.
 *
 * To use Convex properly:
 * 1. Set up your Convex deployment at https://dashboard.convex.dev
 * 2. Add your VITE_CONVEX_URL to .env.local
 * 3. Run `npx convex dev` to generate proper types
 */

import * as personas from "../personas";
import * as experiments from "../experiments";
import * as users from "../users";
import * as responses from "../responses";

export const api = {
  personas,
  experiments,
  users,
  responses,
};
