/* eslint-disable */
/**
 * Generated data model types for Convex
 *
 * This file is auto-generated by running `npx convex dev`
 * For now, this is a manually created stub until Convex is properly configured.
 */

import { GenericId } from "convex/values";

export type Id<TableName extends string> = GenericId<TableName>;
