/* eslint-disable */
/**
 * Generated data model stub for Convex
 *
 * This file is auto-generated by running `npx convex dev`
 * For now, this is a manually created stub until Convex is properly configured.
 */

export type Id<TableName extends string> = string & { __tableName: TableName };
