/* eslint-disable */
/**
 * Generated server types for Convex
 *
 * This file is auto-generated by running `npx convex dev`
 * For now, this is a manually created stub until Convex is properly configured.
 */

import {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
} from "convex/server";
import { AnyDataModel, GenericId } from "convex/server";

export declare const query: QueryBuilder<AnyDataModel, "public">;
export declare const mutation: MutationBuilder<AnyDataModel, "public">;
export declare const action: ActionBuilder<AnyDataModel, "public">;
export declare const httpAction: HttpActionBuilder;

export type Id<TableName extends string> = GenericId<TableName>;
