/* eslint-disable */
/**
 * Generated server stub for Convex
 *
 * This file is auto-generated by running `npx convex dev`
 * For now, this is a manually created stub until Convex is properly configured.
 */

// Stub implementations that satisfy the type requirements
export const query = ((config: any) => config) as any;
export const mutation = ((config: any) => config) as any;
export const action = ((config: any) => config) as any;
export const httpAction = ((handler: any) => handler) as any;

export type Id<TableName extends string> = string & { __tableName: TableName };
